# /etc/nginx/sites-available/dev-api

server {
    listen 8080;
    server_name localhost;
    
    client_max_body_size 10M;
    
  
    location /api/ {
        proxy_pass http://127.0.0.1:8000/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Cookie $http_cookie;
        proxy_request_buffering off;
    }
    
  
    location /static/ {
        proxy_pass http://127.0.0.1:8000/static/;
        proxy_set_header Host $host;
    }
    
 
    location /health {
        proxy_pass http://127.0.0.1:8000/health;
        proxy_set_header Host $host;
    }
    
  
    location /swagger/ {
        proxy_pass http://127.0.0.1:8000/swagger/;
        proxy_set_header Host $host;
    }
    

    location /auth/ {
        proxy_pass http://127.0.0.1:8000/auth/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Cookie $http_cookie;
    }
}